chat-mute-backend
katataku/ft_transcendence pull request #84
Opened 2023-02-12 13:30 UTC by katataku

resolve #74 

- [ ] ミュート用のテーブル定義追加
- [ ] ミュート用のAPI作成
- [ ] モーダル画面の追加
- [ ] 新規作成APIのswagger定義追加

2023-02-12 14:23 UTC, tharaguc requested changes
API用のインターフェイスをDtoにして、controllerとserviceの引数をDtoにできますか？

2023-02-13 10:03 UTC, katataku commented
> API用のインターフェイスをDtoにして、controllerとserviceの引数をDtoにできますか？
> 
> > https://github.com/katataku/ft_transcendence/tree/feat/profile-1/backend/src
> 
> このブランチみたいな感じでお願いします。

修正してみました！意図通りか確認お願いします！

2023-02-14 04:00 UTC, shima8823 approved these changes

2023-02-14 07:37 UTC, tharaguc approved these changes
大丈夫です！ありがとうございます。

2023-02-14 16:35 UTC, AuroraSloan approved these changes

2023-02-14 16:35 UTC, merged